### ISSUE TITLE
telegram integration

### ISSUE THREAD

**Issue by opheliagame** [flameddd/screenshots-ci-action#17]
i am trying to setup the telegram integration but it doesn't seem to be working for me. I have created both repository secret and environment secret. The action runs without error but I am not receiving any message. Am i missing something?
Here is my workflow yaml file 

```
name: screenshots ci actions
on:
  page_build:
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://an-online-reading-room.github.io/reading-room-platform
        devices: iPhone 6, Nexus 10
        noDesktop: true
      env:
        TELE_CHAT_ID: ${{ secrets.TELE_CHAT_ID }}
        TELE_BOT_TOKEN: ${{ secrets.TELE_BOT_TOKEN }}

    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://an-online-reading-room.github.io/reading-room-platform/stories
        devices: iPhone 6, Nexus 10
        noDesktop: true
      env:
        TELE_CHAT_ID: ${{ secrets.TELE_CHAT_ID }}
        TELE_BOT_TOKEN: ${{ secrets.TELE_BOT_TOKEN }}
```
