### ISSUE TITLE
Dynamic URLs from Netlify preview

### ISSUE THREAD

**Issue by LukaHarambasic** [flameddd/screenshots-ci-action#4]
Hi,

I wanted to ask if you know if it's possible to combine this action with the default Netlify setup.

Netlify hosts a preview of the current build, that's linked in every new PR. Now I want to have screenshots from this preview on multiple screen sizes. Do you know if that's possible?

Thanks,
Luka :)

**Comment by flameddd** [comment]
Hi @LukaHarambasic 

Thanks for your submit this issue. I never deploy **Netlify** before. Could you provide more references for me. (how you deploy? any Netlify document could be my ref? )

I guess your process is 
1. push code to github
2. trigger Github Action to deploy **Netlify**
3. and you want to generate screenshots from **step2**

right ?

For now, I think there are two possible solution.
1. Is it possible to get **step2** 's URL ? If ANS is YES, It's possible to pass URL to **screenshots-ci-action**
    - https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjobs_idoutputs

2. deploy site in Github Action
    - I think in most of cases, We need run script like `npm run build` to bundle file. So We can launch a server like [lite-server](https://www.npmjs.com/package/lite-server) and deploy site then visit **localhost:port**. (I learned this from [lighthouse-ci](https://github.com/treosh/lighthouse-ci-action), but I can not find document right now ): )

I' m happy to dig into this case in this weekend. It would be very helpful if you provide more information.

Your case is ?
  - Static site?
  - frontend with server?
  - any **Netlify** document or blog or articles could be reference ?

thanks

**Comment by LukaHarambasic** [comment]
HI @flameddd,

thanks for the fast answer! :)

Netlify Setup: https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/

So Netlify just builds automatically every time I push something. I don't have the Actions under my control, I'm not even sure if it's possible if Netlify and GitHub Actions play together.

And if a new PR is opened the build process and the following steps are executed:
![image](https://user-images.githubusercontent.com/22857823/88889761-e7633580-d240-11ea-8263-30982c96746e.png)
https://github.com/LukaHarambasic/active-ambassadors/pull/24

The last step is the interesting one as there is the preview included.

I'm currently building a Static site which is hosted on Netlify and consumes data from Prismic & Airtable - nothing crazy :D

Do you need more information?

Cheers,
Luka

**Comment by flameddd** [comment]
thanks! I will take a look in this weekend.

**Comment by flameddd** [comment]
Hi @LukaHarambasic 


## tl;tr

### 1. find out your "pull request's netlify's Pages changed checkname
steps
1. go to one of **pull request**
2. go to **Checks** tab
3. there is a netlify checks on left list
4. copy "**Pages changed** ... " checkname
    - e.x. **"Pages changed - modest-spence-711b92"**

![image](https://user-images.githubusercontent.com/22259196/89117111-bf3c3680-d4cd-11ea-8b18-4a9b31040fb6.png)  
![image](https://user-images.githubusercontent.com/22259196/89117116-c82d0800-d4cd-11ea-8e09-ffaeb2d3b117.png)


### 2. find out your **netlify** site name
steps
1. go to https://app.netlify.com/ and copy site name
    - e.x. modest-spence-711b92

![image](https://user-images.githubusercontent.com/22259196/89117145-20640a00-d4ce-11ea-934a-b9739354c217.png)


### 3. create ".github/workflows/screenshots.yml" on the root
steps
1. copy/past yaml example (in below) to **screenshots.yml**
2. replace **netlify_PAGE_CHANGED_CHECK_NAME** with your checkname (with single quote, bcuz checkName string have space)
    - e.x. `checkName: 'Pages changed - modest-spence-711b92'`
3. replace **netlify_SITE_NAME** with your site name
    - e.x. `site_name: 'modest-spence-711b92'`
4. (set your **screenshots-ci-action** config. example only for desktop screenshot)

![image](https://user-images.githubusercontent.com/22259196/89117298-463dde80-d4cf-11ea-9ed1-399be5fda0bd.png)

### finally
- create pull request
- Github Action will start, but waiting for netlify deploy and checks
  - if we push new commit, Github Action and netlify deploy will trigger again

I tested several times, I think this workaround solution works fine ^^|||

my test repo (fork from your's)
- action: https://github.com/flameddd/active-ambassadors/runs/936997932?check_suite_focus=true
- pull request: https://github.com/flameddd/active-ambassadors/pull/15
- workflow YAML: https://github.com/flameddd/active-ambassadors/blob/c7d35a27d064c47f8cf2e948acc7c12d27a5f007/.github/workflows/screenshots-workflow2.yml
- (I will **DELETE** this fork in near future)

### workflow yaml example
```yaml
name: Screenshots-ci

on: [pull_request]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for Pages changed to neutral
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-Netlify
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        checkName: netlify_PAGE_CHANGED_CHECK_NAME
    - name: Get Preview URL and generate screenshot after Netlify check done
      if: steps.wait-for-Netlify.outputs.conclusion == 'neutral'
      uses: jakepartusch/wait-for-netlify-action@v1
      id: waitFor200
      with:
        site_name: netlify_SITE_NAME
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v1.1.0
      with:
        url: ${{ steps.waitFor200.outputs.url }}
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots
```

----------------------------------------------------------------------
## About **"jakepartusch/wait-for-netlify-action"** Action
- "wait-for-netlify-action" will wait and help us to find out "preview's url"
  - `${{ steps.waitFor200.outputs.url }}`
- unforturely, there is a Issue and not solve yet
  - [Does not reliably work when adding a commit to an existing deploy preview](https://github.com/JakePartusch/wait-for-netlify-action/issues/6)
  - issue URL: https://github.com/JakePartusch/wait-for-netlify-action/issues/6

So, I Use **"fountainhead/action-wait-for-check@"** Action try to solve it.  
And **action-wait-for-check** 's work looks fine !  

In the future, we can remove `fountainhead/action-wait-for-check` after [Issue #6](https://github.com/JakePartusch/wait-for-netlify-action/issues/6) solved

e.x. 
```yaml
name: Successful Deploy Action Example

on: [pull_request]

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: netlify_SITE_NAME
    - uses: actions/checkout@v2
    ...
       with:
         url: ${{ steps.waitFor200.outputs.url }}
```


## About **"fountainhead/action-wait-for-check"** Action
- there are **four netlify check names**
  - Header rules - modest-spence-...
  - Pages changed - modest-spence-...
  - Redirect rules - modest-spence-...
  - Mixed content - modest-spence-...

I chose **'Pages changed'** as check target **by intuition**
- rest of checks seems do nothing
- I don't know why **'Pages changed'** check's final **conclusion** is **'neutral'**
  - why is not **'success'**, like **'Mixed content'** check

### The things I want to say is
**As long as your netlify USE CASE become more COMPLICATE in the future**
- maybe there will be another more appropriate **check name** can use (e.x. deploy check?)
- maybe the **conclusion** become **'success'**, but NOT **'neutral'**

bcuz I am totally **newbie in netlify**, I just want to mention those things I not sure

------------------------------------------------------------------

## About on **deployment_status**
Before I find out **"jakepartusch/wait-for-netlify-action"** Action. I read a blog post.  
- https://webcloud.se/blog/2020-02-16-github-actions-preview-deploys/

In this post said  
![image](https://user-images.githubusercontent.com/22259196/89118016-2ad5d200-d4d5-11ea-885b-1785dbb2300c.png)  
![image](https://user-images.githubusercontent.com/22259196/89118018-30cbb300-d4d5-11ea-801f-c58e07895c77.png)  

like this
```yaml
# .github/workflows/example_workflow.yml
name: Successful Deploy Action Example
on: deployment_status
jobs:
  build:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: XYZ
        run: npm run xyz
        env:
          DEPLOY_URL: ${{ github.event.deployment_status.target_url }}
```

**BUT** I have tried lots of times. **workflow NEVER be triggered by deployment_status (or deploymene)**   

and
1. I can not find too much information on 
    - https://community.netlify.com/
    - https://docs.netlify.com/
2. There exists some **Github Actions** like **wait-for-netlify-action** (like a webhook)

SO, I guess the blog post is **misleading** (maybe only **Zeit** can work)

But I think netlify will implement those feature one day. If they does  (I hope)  
We can use **deployment_status** as hooks  
It would be most simple and clear solution  

---------------------------------------------------

## In the end
1. I would be thankful, **does this solution work for you?**
2. I will keep this issue open for a while, feel free to discuss your use case


thanks a lot.
