### ISSUE TITLE
add manually trigger code example

### ISSUE THREAD

**Issue by flameddd** [flameddd/screenshots-ci-action#9]
# add manually trigger code example

**Comment by flameddd** [comment]
# manual trigger example 1
- input target **URL**
- generate **desktop** screenshots

```yaml
name: manually screenshots action
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The website URL (ex: https://github.com/)'     
        required: true
        default: ''

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: ${{ github.event.inputs.url }}
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots
```


# manual trigger example 2
- input target **URL**, setting mobile **devices**
- generate **desktop** and **mobiles** screenshots


```yaml
name: manually screenshots action
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The website URL (ex: https://github.com/)'     
        required: true
        default: ''
      devices:
        description: 'Specific mobile devices. Use comma(,) to separate devices name. More info: https://github.com/flameddd/screenshots-ci-action'
        required: false
        default: ''

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-ci-action
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: ${{ github.event.inputs.url }}
        devices: ${{ github.event.inputs.devices }}
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-screenshots
```


# manual trigger example 3
- input **2** target **URL**
- generate **mobiles** screenshots

```yaml
name: manually screenshots action
on:
  workflow_dispatch:
    inputs:
      url1:
        description: 'The website URL (ex: https://github.com/)'     
        required: true
        default: ''
      url2:
        description: 'The website URL (ex: https://stackoverflow.com/)'     
        required: true
        default: ''

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-url1-action
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: ${{ github.event.inputs.url1 }}
        devices: iPhone 6,iPhone 6 landscape
        noDesktop: true
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-url1-screenshots
    - run: rm ./screenshots/*

    - name: screenshots-url2-action
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: ${{ github.event.inputs.url2 }}
        devices: iPhone 6,iPhone 6 landscape
        noDesktop: true
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-url2-screenshots
    - run: rm ./screenshots/*
```


```yaml
name: screenshots ci actions
on:
  push:
    branches:
    - master

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install puppeteer-headful
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
    - name: screenshots-desktop-facebook
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://www.facebook.com/
        devices: iPhone 6,iPhone 6 landscape
        noDesktop: true
    - uses: actions/upload-artifact@v2
      with:
        name: Download-desktop-screenshots
        path: screenshots
    - run: rm ./screenshots/*

    - name: screenshots-mobile-facebook
      uses: flameddd/screenshots-ci-action@v1.1.1
      with:
        url: https://m.facebook.com/
        devices: iPhone 6,iPhone 6 landscape
        noDesktop: true
    - uses: actions/upload-artifact@v2
      with:
        path: screenshots
        name: Download-mobile-screenshots
    - run: rm ./screenshots/*
```
